<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: index.latte */
final class Template_d65fb3215c extends Latte\Runtime\Template
{
	public const Source = 'index.latte';


	public function main(array $ʟ_args): void
	{
		echo '
<p>
    Hello, test.
</p>';
	}
}
